$ cat nginx-baduri.conf
[Definition]
allowipv6 = auto

failregex =
    # traversal / encoding / injection
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*(\.\.|%%2e|%%2f|\\\\x5c|\\\\\\\\).*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*\\$\\(.*\\).*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*invokefunction.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*XDEBUG_SESSION_START.*"

    # looking for any PHP URI to defend against shell hunting
#    (?i)^<HOST> .* "(GET|POST|HEAD) /.*\.php.*"

    # block trying for admin and login pages
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*admin.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*(login|logon|config|setup|settings|gate|panel).*"
    (?i)^<HOST> .* "(GET|POST|HEAD) .*(phpmyadmin|pma|mysql|sql-admin|dbadmin).*"

    # Common Vulnerability Targets (Routers/IoT/Log4J)
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/HNAP1.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/luci/.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/rpcform/.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/actuator/.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/druid/.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*(boaform|cgi-bin|autodiscover|actuator).*"

    # Shell & Remote Execution attempts
    (?i)^<HOST> .* "(GET|POST|HEAD) .*(shell|cmd|exec|eval|system|powershell).*"

    # Apple Mac noise
#    (?i)^<HOST> .* "(GET|POST|HEAD) .*apple-touch-icon.*"

    # wordpress / cms scanning (you are not running WP)
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/wp-.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/wordpress/.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/joomla/.*"

    # Backup & Archive files (Scanners look for leaked zip files)
    (?i)^<HOST> .* "(GET|POST|HEAD) .*(backup|backup-.*|old|site|www|db)\.(zip|tar|gz|sql|rar|7z).*"

    # phpunit RCE paths (ALL variants)
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/vendor/.*/phpunit/.*/eval-stdin\\.php.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/phpunit/.*/eval-stdin\\.php.*"

    # sensitive files
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*(\.env|\.git|\.ssh|\.htaccess|\.aws).* "
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*(config\.php|web\.config|settings\.py|composer\.json).*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*config\\.json.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*license\\.txt.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*phpinfo.*"

    # generic exploit-style PHP filenames
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*/[a-zA-Z0-9_-]{1,12}\\.php(\\?|$)"

ignoreregex =
