[Definition]

failregex =

    # Empty User-Agent (Hyphen)
    (?i)^<HOST> .* "[A-Z]+ .*" \d+ \d+ ".*" "-"
    # fake Mozillas
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* "Mozilla/[0-9]\.0"

    # Go http client
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* "Go-http-client/.*"

    # bot strings
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*Hello World.*"
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*libredtail-http.*"

    # zgrab (Fixed)
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*zgrab.*"

    # keydrop
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* "Keydrop\.io/.*"

    # Opera with chinese or russian language agents
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* "Opera/.*(zh-tw|ru).*"

    # python requests
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* "python-requests/.*"

    # Terracotta
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*TerraCotta.*"

    # xfa family
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*xfa1.*"

    # generic scanners
    (?i)^<HOST> .* "(GET|POST|HEAD|OPTIONS) .*" .* ".*(libwww|masscan|nmap|sqlmap).*"

ignoreregex =
